import { describe, expect, it } from "vitest";

import {
  cloudSetupNeedsMachineConfirmation,
  createCloudSetupClient,
  formatCloudPatchPlan,
  normalizeCloudOrigin,
  planCloudPatch,
  reportCloudSetupEvent,
} from "../src/cloud-setup.js";

describe("Chumbo Cloud setup patch", () => {
  const input = {
    root: "/repo",
    functionSlug: "mcp",
    currentSource:
      'import { createSupabaseMcp } from "chumbo";\nconst app = createSupabaseMcp({\n  name: "Notes",\n  tools: [],\n});\n',
    currentAdapter: null,
    onEventSnippet: "export async function chumboCloudOnEvent() {}",
    onSurfaceSnippet: "export async function chumboCloudOnSurface() {}",
  };

  it("adds one generated adapter and both hooks", () => {
    const plan = planCloudPatch(input);
    expect(plan.changed).toBe(true);
    expect(plan.functionSource).toContain('from "./chumbo-cloud.ts"');
    expect(plan.functionSource).toContain("onEvent: chumboCloudOnEvent,");
    expect(plan.functionSource).toContain("onSurface: chumboCloudOnSurface,");
    expect(plan.adapter).toContain("Generated by Chumbo Cloud");
    expect(plan.changes).toEqual([
      expect.objectContaining({
        path: "/repo/supabase/functions/mcp/index.ts",
        action: "update",
      }),
      expect.objectContaining({
        path: "/repo/supabase/functions/mcp/chumbo-cloud.ts",
        action: "create",
      }),
    ]);
  });

  it("is idempotent", () => {
    const first = planCloudPatch(input);
    const second = planCloudPatch({
      ...input,
      currentSource: first.functionSource,
      currentAdapter: first.adapter,
    });
    expect(second.changed).toBe(false);
  });

  it("refuses to overwrite a custom lifecycle hook", () => {
    expect(() =>
      planCloudPatch({
        ...input,
        currentSource: input.currentSource.replace(
          'name: "Notes",',
          'name: "Notes",\n  onEvent: customHook,',
        ),
      }),
    ).toThrow(/custom lifecycle hook/u);
  });

  it("refuses a function name that could escape the approved directory", () => {
    expect(() =>
      planCloudPatch({ ...input, functionSlug: "../../../../tmp" }),
    ).toThrow(/invalid Edge Function name/u);
  });

  it("shows every exact line that setup will add", () => {
    const preview = formatCloudPatchPlan(planCloudPatch(input), input.root);
    expect(preview).toContain("update supabase/functions/mcp/index.ts");
    expect(preview).toContain("+   onEvent: chumboCloudOnEvent,");
    expect(preview).toContain("create supabase/functions/mcp/chumbo-cloud.ts");
    expect(preview).toContain(
      "+ export async function chumboCloudOnSurface() {}",
    );
  });
});

describe("Chumbo Cloud setup client", () => {
  const eventSnippet = `import type { SupabaseMcpLifecycleEvent } from "chumbo";
const secret = "CHUMBO_CLOUD_ANALYTICS_BRIDGE_HMAC_V1";
export async function chumboCloudOnEvent(_event: SupabaseMcpLifecycleEvent) { void secret; }`;
  const surfaceSnippet = `import type { SupabaseMcpSurfaceProof } from "chumbo";
const secret = "CHUMBO_CLOUD_ANALYTICS_BRIDGE_HMAC_V1";
export async function chumboCloudOnSurface(_proof: SupabaseMcpSurfaceProof) { void secret; }`;

  it("refuses to open a pairing URL from another origin", async () => {
    const fetchImplementation = async () =>
      new Response(
        JSON.stringify({
          schemaVersion: 1,
          deviceCode: "a".repeat(43),
          userCode: "23456-789AB",
          verificationUriComplete:
            "https://example.com/setup/pair?code=23456-789AB",
          expiresAt: "2026-09-14T18:00:00.000Z",
          intervalSeconds: 2,
        }),
        { status: 201, headers: { "content-type": "application/json" } },
      );
    await expect(
      createCloudSetupClient(
        "https://app.chumbo.dev",
        fetchImplementation as typeof fetch,
      ).start({
        codeChallenge: "a".repeat(43),
        deviceName: "computer",
        agentName: "agent",
      }),
    ).rejects.toMatchObject({ code: "invalid_response" });
  });

  it("keeps the scoped token in authorization rather than request bodies", async () => {
    const requests: { url: string; init: RequestInit }[] = [];
    const fetchImplementation = async (
      url: string | URL | Request,
      init?: RequestInit,
    ) => {
      requests.push({ url: String(url), init: init ?? {} });
      return new Response(
        JSON.stringify({
          schemaVersion: 1,
          sessionId: "018f47c2-4f48-7b9b-8f2f-5af629221111",
          project: { ref: "abcdefghijklmnopqrst", name: "Project" },
          functionSlug: "mcp",
          integration: {
            secretName: "CHUMBO_CLOUD_ANALYTICS_BRIDGE_HMAC_V1",
            onEventSnippet: eventSnippet,
            onSurfaceSnippet: surfaceSnippet,
          },
        }),
        { status: 200, headers: { "content-type": "application/json" } },
      );
    };
    await createCloudSetupClient(
      "https://app.chumbo.dev",
      fetchImplementation as typeof fetch,
    ).task("scoped-token");
    const request = requests[0]!;
    expect(request.url).toBe("https://app.chumbo.dev/api/setup/device/task");
    expect((request.init.headers as Record<string, string>).Authorization).toBe(
      "Bearer scoped-token",
    );
    expect(request.init.body).toBeUndefined();
  });

  it("accepts only versioned token and verification receipts", async () => {
    const fetchImplementation = async (url: string | URL | Request) => {
      const path = new URL(String(url)).pathname;
      if (path.endsWith("/token")) {
        return new Response(
          JSON.stringify({
            schemaVersion: 1,
            accessToken: "b".repeat(43),
            tokenType: "Bearer",
            expiresAt: "2026-09-14T18:00:00.000Z",
          }),
          { status: 200, headers: { "content-type": "application/json" } },
        );
      }
      return new Response(
        JSON.stringify({ schemaVersion: 1, state: "verified" }),
        { status: 200, headers: { "content-type": "application/json" } },
      );
    };
    const client = createCloudSetupClient(
      "https://app.chumbo.dev",
      fetchImplementation as typeof fetch,
    );
    await expect(client.token("a".repeat(43), "c".repeat(43))).resolves.toEqual(
      {
        accessToken: "b".repeat(43),
        expiresAt: "2026-09-14T18:00:00.000Z",
      },
    );
    await expect(client.verify("b".repeat(43))).resolves.toEqual({
      state: "verified",
    });
  });

  it("rejects an invalid task before its path or code can be used", async () => {
    const fetchImplementation = async () =>
      new Response(
        JSON.stringify({
          schemaVersion: 1,
          sessionId: "018f47c2-4f48-7b9b-8f2f-5af629221111",
          project: { ref: "abcdefghijklmnopqrst", name: "Project" },
          functionSlug: "../../../../tmp",
          integration: {
            secretName: "CHUMBO_CLOUD_ANALYTICS_BRIDGE_HMAC_V1",
            onEventSnippet: eventSnippet,
            onSurfaceSnippet: surfaceSnippet,
          },
        }),
        { status: 200, headers: { "content-type": "application/json" } },
      );
    await expect(
      createCloudSetupClient(
        "https://app.chumbo.dev",
        fetchImplementation as typeof fetch,
      ).task("scoped-token"),
    ).rejects.toMatchObject({ code: "invalid_response" });
  });

  it("normalizes a malformed Cloud error without throwing an internal type error", async () => {
    const fetchImplementation = async () =>
      new Response("null", {
        status: 503,
        headers: { "content-type": "application/json" },
      });
    await expect(
      createCloudSetupClient(
        "https://app.chumbo.dev",
        fetchImplementation as typeof fetch,
      ).task("scoped-token"),
    ).rejects.toMatchObject({
      code: "request_failed",
      message: "Chumbo Cloud setup did not finish.",
    });
  });

  it("requires HTTPS except for an explicit loopback development origin", () => {
    expect(normalizeCloudOrigin("https://app.chumbo.dev")).toBe(
      "https://app.chumbo.dev",
    );
    expect(normalizeCloudOrigin("http://127.0.0.1:3000")).toBe(
      "http://127.0.0.1:3000",
    );
    expect(() => normalizeCloudOrigin("http://example.com")).toThrow(
      /HTTPS origin/u,
    );
  });
});

describe("Chumbo Cloud setup command policy", () => {
  it("never prompts for confirmation in JSON mode", () => {
    expect(
      cloudSetupNeedsMachineConfirmation({
        machine: true,
        yes: false,
        planOnly: false,
      }),
    ).toBe(true);
    expect(
      cloudSetupNeedsMachineConfirmation({
        machine: false,
        yes: false,
        planOnly: false,
      }),
    ).toBe(false);
  });

  it("keeps progress reporting failures from hiding completed local work", async () => {
    const warnings: string[] = [];
    await expect(
      reportCloudSetupEvent(
        async () => {
          throw new Error("temporarily unavailable");
        },
        { kind: "change_applied", summary: "Applied." },
        (warning) => warnings.push(warning),
      ),
    ).resolves.toBeUndefined();
    expect(warnings).toEqual([
      "Cloud could not record change_applied; setup continued.",
    ]);
  });
});
