import { describe, expect, it } from "vitest";

import { createCloudSetupClient, planCloudPatch } from "../src/cloud-setup.js";

describe("Chumbo Cloud setup patch", () => {
  const input = {
    root: "/repo",
    functionSlug: "mcp",
    currentSource:
      'import { createSupabaseMcp } from "chumbo";\nconst app = createSupabaseMcp({\n  name: "Notes",\n  tools: [],\n});\n',
    currentAdapter: null,
    onEventSnippet: "export async function chumboCloudOnEvent() {}",
    onSurfaceSnippet: "export async function chumboCloudOnSurface() {}",
  };

  it("adds one generated adapter and both hooks", () => {
    const plan = planCloudPatch(input);
    expect(plan.changed).toBe(true);
    expect(plan.functionSource).toContain('from "./chumbo-cloud.ts"');
    expect(plan.functionSource).toContain("onEvent: chumboCloudOnEvent,");
    expect(plan.functionSource).toContain("onSurface: chumboCloudOnSurface,");
    expect(plan.adapter).toContain("Generated by Chumbo Cloud");
  });

  it("is idempotent", () => {
    const first = planCloudPatch(input);
    const second = planCloudPatch({
      ...input,
      currentSource: first.functionSource,
      currentAdapter: first.adapter,
    });
    expect(second.changed).toBe(false);
  });

  it("refuses to overwrite a custom lifecycle hook", () => {
    expect(() =>
      planCloudPatch({
        ...input,
        currentSource: input.currentSource.replace(
          'name: "Notes",',
          'name: "Notes",\n  onEvent: customHook,',
        ),
      }),
    ).toThrow(/custom lifecycle hook/u);
  });
});

describe("Chumbo Cloud setup client", () => {
  it("keeps the scoped token in authorization rather than request bodies", async () => {
    const requests: { url: string; init: RequestInit }[] = [];
    const fetchImplementation = async (
      url: string | URL | Request,
      init?: RequestInit,
    ) => {
      requests.push({ url: String(url), init: init ?? {} });
      return new Response(
        JSON.stringify({
          sessionId: "session",
          project: { ref: "project", name: "Project" },
          functionSlug: "mcp",
          integration: {
            secretName: "secret",
            onEventSnippet: "event",
            onSurfaceSnippet: "surface",
          },
        }),
        { status: 200, headers: { "content-type": "application/json" } },
      );
    };
    await createCloudSetupClient(
      "https://app.chumbo.dev",
      fetchImplementation as typeof fetch,
    ).task("scoped-token");
    const request = requests[0]!;
    expect(request.url).toBe("https://app.chumbo.dev/api/setup/device/task");
    expect((request.init.headers as Record<string, string>).Authorization).toBe(
      "Bearer scoped-token",
    );
    expect(request.init.body).toBeUndefined();
  });
});
