import { defineConfig } from "tsdown";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/app.ts",
    "src/testing.ts",
    "src/cli.ts",
    "src/types.ts",
    "src/results.ts",
    "src/cli-auth.ts",
    "src/cli-host.ts",
    "src/cli-package.ts",
    "src/cli-surface.ts",
  ],
  format: "esm",
  dts: true,
  hash: false,
  clean: true,
  sourcemap: true,
  target: "es2022",
  platform: "neutral",
  external: [
    "node:child_process",
    "node:crypto",
    "node:fs/promises",
    "node:http",
    "node:os",
    "node:path",
    "node:readline/promises",
    "node:url",
    "node:util",
    "@modelcontextprotocol/server",
    "@modelcontextprotocol/client",
    "@modelcontextprotocol/ext-apps",
    "@napi-rs/keyring",
    "@supabase/server",
    "@supabase/server/core",
    "@supabase/supabase-js",
    "zod",
  ],
});
