import { access, readFile } from "node:fs/promises";
import { join } from "node:path";

export type SetupAuthMode = "oauth" | "api-key" | "bearer" | "public";
export type ApiKeyStrategy = "static" | "verifier" | "unknown";

export interface GeneratedAuthInspection {
  mode: SetupAuthMode;
  apiKeyStrategy?: ApiKeyStrategy;
  stateNamespace?: string;
}

export interface RemoteVerificationEvidence {
  attempted: boolean;
  reachable: boolean;
  runtimeReached: boolean;
  authGateObserved: boolean;
  credentialSupplied: boolean;
  credentialAccepted?: boolean;
  mcpDiscoveryVerified: boolean;
  resourceUrlVerified?: boolean;
  runtimeVersion?: string;
  authMode?: SetupAuthMode;
  apiKeyStrategy?: ApiKeyStrategy;
}
export type SetupStepStatus =
  | "complete"
  | "ready"
  | "needs_user_action"
  | "blocked"
  | "skipped";

export interface SetupStep {
  id: string;
  title: string;
  status: SetupStepStatus;
  detail: string;
  command?: string;
  url?: string;
}

export interface SetupReport {
  schemaVersion: 1;
  command: "setup" | "status";
  status:
    | "planned"
    | "ready"
    | "needs_confirmation"
    | "needs_user_action"
    | "blocked"
    | "complete";
  projectRoot: string;
  functionName: string;
  auth: SetupAuthMode;
  authStrategy?: ApiKeyStrategy;
  localEndpoint: string;
  endpoint?: string;
  upstreamEndpoint?: string;
  files: Array<{
    path: string;
    status: "create" | "unchanged" | "update" | "conflict";
  }>;
  steps: SetupStep[];
  nextActions: SetupStep[];
  resumeCommand: string;
  agentHandoff: {
    documentationServerUrl: string;
    prompt: string;
    skillInstallCommand: string;
  };
  verification?: RemoteVerificationEvidence;
}

export const SUPA_MCP_DOCUMENTATION_SERVER_URL =
  "https://dxrpeagddrpbezbkgvdv.supabase.co/functions/v1/docs-mcp";

export interface BuildSetupReportOptions {
  command: "setup" | "status";
  projectRoot: string;
  functionName: string;
  localEndpoint: string;
  auth: SetupAuthMode;
  consent: "none" | "minimal";
  files: SetupReport["files"];
  applied: boolean;
  planned: boolean;
  needsConfirmation?: boolean;
  localChecks?: "complete" | "ready" | "blocked" | "skipped";
  migrations?: "complete" | "ready" | "blocked" | "skipped";
  deployed?: boolean;
  remoteVerified?: boolean;
  remoteAttempted?: boolean;
  remoteReady?: boolean;
  verification?: RemoteVerificationEvidence;
  apiKeyStrategy?: ApiKeyStrategy;
  endpoint?: string;
  publicUrl?: string;
  publicUrlConfigured?: boolean;
  projectRef?: string;
  checkDetail?: string;
  localCheckCommand?: string;
  migrationDetail?: string;
  durableState?: boolean;
  deployDetail?: string;
  verifyDetail?: string;
}

async function exists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

export async function inspectGeneratedAuth(
  root: string,
  functionName: string,
): Promise<GeneratedAuthInspection | undefined> {
  const path = join(root, "supabase", "functions", functionName, "index.ts");
  if (!(await exists(path))) return undefined;
  const source = await readFile(path, "utf8");
  const stateNamespace = /namespaces:\s*\{\s*["']([^"']+)["']\s*:/.exec(
    source,
  )?.[1];
  const state = stateNamespace ? { stateNamespace } : {};
  // Composed auth is intentionally configured in application code rather than
  // generated by the beginner setup flow. Doctor detects it from runtime
  // headers instead of misclassifying one nested strategy as the whole server.
  if (/mode:\s*["']multi["']/.test(source)) return undefined;
  if (/mode:\s*["']public["']/.test(source)) {
    return { mode: "public", ...state };
  }
  if (/mode:\s*["']api-key["']/.test(source)) {
    const apiKeyStrategy: ApiKeyStrategy = /\bverify\s*(?:\(|:)/.test(source)
      ? "verifier"
      : /MCP_API_KEY/.test(source)
        ? "static"
        : "unknown";
    return { mode: "api-key", apiKeyStrategy, ...state };
  }
  if (/mode:\s*["']bearer["']/.test(source)) {
    return { mode: "bearer", ...state };
  }
  if (/mode:\s*["']oauth["']/.test(source)) {
    return { mode: "oauth", ...state };
  }
  return undefined;
}

export async function detectGeneratedAuth(
  root: string,
  functionName: string,
): Promise<SetupAuthMode | undefined> {
  return (await inspectGeneratedAuth(root, functionName))?.mode;
}

export async function detectLinkedProjectRef(
  root: string,
): Promise<string | undefined> {
  for (const path of [
    join(root, "supabase", ".temp", "project-ref"),
    join(root, ".supabase", "project-ref"),
  ]) {
    if (!(await exists(path))) continue;
    const value = (await readFile(path, "utf8")).trim();
    if (/^[a-z0-9-]+$/i.test(value)) return value;
  }
  return undefined;
}

export function endpointFor(
  projectRef: string | undefined,
  functionName: string,
): string | undefined {
  return projectRef
    ? `https://${projectRef}.supabase.co/functions/v1/${functionName}`
    : undefined;
}

export function normalizePublicUrl(value: string): string {
  const url = new URL(value);
  if (!["http:", "https:"].includes(url.protocol)) {
    throw new Error("--public-url must use http or https");
  }
  if (url.username || url.password || url.search || url.hash) {
    throw new Error(
      "--public-url cannot contain credentials, a query string, or a fragment",
    );
  }
  url.pathname = url.pathname.replace(/\/+$/, "") || "/";
  return url.href;
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'"'"'`)}'`;
}

function overallStatus(
  options: BuildSetupReportOptions,
  steps: readonly SetupStep[],
): SetupReport["status"] {
  if (options.planned) {
    return options.needsConfirmation ? "needs_confirmation" : "planned";
  }
  if (steps.some((step) => step.status === "blocked")) return "blocked";
  if (options.remoteVerified) return "complete";
  if (steps.some((step) => step.status === "needs_user_action")) {
    return "needs_user_action";
  }
  return "ready";
}

export function buildSetupReport(
  options: BuildSetupReportOptions,
): SetupReport {
  const upstreamEndpoint = endpointFor(
    options.projectRef,
    options.functionName,
  );
  const publicUrl = options.publicUrl
    ? normalizePublicUrl(options.publicUrl)
    : undefined;
  const endpoint = options.endpoint ?? publicUrl ?? upstreamEndpoint;
  const localEndpoint = options.localEndpoint;
  const apiKeyStrategy = options.apiKeyStrategy ?? "static";
  const localServeCommand =
    options.auth === "api-key" && apiKeyStrategy === "static"
      ? `npx chumbo dev --function ${options.functionName} --env-file supabase/functions/.env.local`
      : `npx chumbo dev --function ${options.functionName}`;
  const localCredential =
    options.auth === "api-key"
      ? ` --token <${apiKeyStrategy === "static" ? "MCP_API_KEY" : "APPLICATION_API_KEY"}>`
      : options.auth === "bearer" || options.auth === "oauth"
        ? " --token <LOCAL_USER_JWT>"
        : "";
  const endpointVerified =
    options.remoteVerified ||
    (options.auth === "oauth" &&
      Boolean(options.verification?.authGateObserved) &&
      Boolean(options.verification?.resourceUrlVerified));
  const steps: SetupStep[] = [
    {
      id: "scaffold",
      title: "Generate the MCP Edge Function",
      status: options.applied ? "complete" : "ready",
      detail: options.applied
        ? "The function entrypoint and Supabase gateway configuration are in place."
        : "Review and apply the generated file plan.",
      command: options.applied
        ? undefined
        : `npx chumbo setup --function ${options.functionName} --auth ${options.auth} --yes --json`,
    },
    {
      id: "local_checks",
      title: "Check the MCP function",
      status: options.localChecks ?? "ready",
      detail:
        options.checkDetail ??
        "Type-check the function and run its contract test when configured.",
      command:
        options.localCheckCommand ??
        `deno task --config supabase/functions/${options.functionName}/deno.json check && deno task --config supabase/functions/${options.functionName}/deno.json test`,
    },
  ];

  if (!options.remoteVerified) {
    steps.push({
      id: "start_local_supabase",
      title: "Start local Supabase",
      status: "ready",
      detail: "Run the application's database, Auth, and Edge Runtime locally.",
      command: "supabase start",
    });
    if (options.auth === "public") {
      steps.push({
        id: "apply_local_migrations",
        title: "Apply local database support",
        status: "ready",
        detail:
          "Apply the generated rate-limit migration to the local database before probing the public MCP.",
        command: "supabase migration up --local",
      });
    }
    steps.push(
      {
        id: "serve_local",
        title: "Serve the MCP locally",
        status: "ready",
        detail:
          options.auth === "api-key" && apiKeyStrategy === "static"
            ? "Provide MCP_API_KEY in the local function environment, then serve the generated function."
            : "Serve the same generated Edge Function that you will deploy.",
        command: localServeCommand,
        url: localEndpoint,
      },
      {
        id: "verify_local",
        title: "Call the generated tool locally",
        status: "ready",
        detail:
          "Initialize MCP, discover tools, and explicitly invoke the generated whoami starter.",
        command: `npx chumbo doctor --function ${options.functionName} --url ${localEndpoint}${localCredential} --call-tool whoami --json`,
        url: localEndpoint,
      },
    );
  }

  if (options.auth === "public") {
    steps.push({
      id: "apply_rate_limit_migration",
      title: "Apply the public rate-limit migration",
      status: options.migrations ?? "ready",
      detail:
        options.migrationDetail ??
        "The public endpoint returns 503 until its Postgres limiter migration is applied.",
      command: "supabase db push --yes",
    });
  }

  if (options.durableState) {
    steps.push({
      id: "apply_durable_state_migration",
      title: "Apply the durable-state migration",
      status: options.migrations ?? "ready",
      detail:
        options.migrationDetail ??
        "The state API remains unavailable until its private table and service-role RPCs are installed.",
      command: "supabase db push --yes",
    });
    steps.push({
      id: "set_state_hmac_secret",
      title: "Set the durable-state identity secret",
      status: options.remoteVerified ? "complete" : "needs_user_action",
      detail:
        "Set a unique deployment secret of at least 32 random bytes. It partitions state by exact credential and is never exposed to capabilities.",
      command: `supabase secrets set ${shellQuote("CHUMBO_STATE_HMAC_KEY=replace-with-at-least-32-random-bytes")} --yes${options.projectRef ? ` --project-ref ${options.projectRef}` : ""}`,
    });
  }

  if (options.auth === "api-key" && apiKeyStrategy === "static") {
    steps.push({
      id: "set_api_key_secret",
      title: "Set the MCP API key secret",
      status: options.remoteVerified ? "complete" : "needs_user_action",
      detail:
        "Set MCP_API_KEY as an Edge Function secret, then give that same key to trusted MCP clients.",
      command: `supabase secrets set ${shellQuote("MCP_API_KEY=replace-with-a-long-random-key")} --yes${options.projectRef ? ` --project-ref ${options.projectRef}` : ""}`,
    });
  }

  if (publicUrl && publicUrl !== upstreamEndpoint) {
    steps.push({
      id: "configure_public_url",
      title: "Set the public MCP URL",
      status:
        options.publicUrlConfigured ||
        options.verification?.resourceUrlVerified ||
        options.remoteVerified
          ? "complete"
          : "ready",
      detail:
        "Tell the Edge Function which clean URL to advertise to MCP clients.",
      command: `supabase secrets set ${shellQuote(`MCP_PUBLIC_URL=${publicUrl}`)} --yes${options.projectRef ? ` --project-ref ${options.projectRef}` : ""}`,
      url: publicUrl,
    });
    steps.push({
      id: "publish_public_route",
      title: "Publish the clean MCP route",
      status:
        options.verification?.runtimeReached &&
        options.verification.resourceUrlVerified
          ? "complete"
          : "needs_user_action",
      detail: upstreamEndpoint
        ? `Proxy ${publicUrl} and every path below it to ${upstreamEndpoint}. The suffix routes provide OAuth discovery.`
        : `Proxy ${publicUrl} and every path below it to the deployed Supabase Edge Function. The suffix routes provide OAuth discovery.`,
      url: publicUrl,
    });
  }

  steps.push({
    id: "deploy",
    title: "Deploy the Edge Function",
    status:
      options.deployed || options.verification?.runtimeReached
        ? "complete"
        : "ready",
    detail:
      options.deployDetail ??
      (options.projectRef
        ? `Deploy to Supabase project ${options.projectRef}.`
        : "Link the Supabase project or pass --project-ref, then deploy."),
    command: `supabase functions deploy ${options.functionName} --no-verify-jwt${options.projectRef ? ` --project-ref ${options.projectRef}` : ""}`,
  });

  if (options.consent === "minimal") {
    steps.push({
      id: "deploy_consent",
      title: "Deploy the fallback consent function",
      status: options.deployed || options.remoteVerified ? "complete" : "ready",
      detail:
        "Deploy the generated fallback only if the application has no consent UI.",
      command: `supabase functions deploy ${options.functionName}-consent --no-verify-jwt${options.projectRef ? ` --project-ref ${options.projectRef}` : ""}`,
    });
  }

  if (options.auth === "oauth") {
    steps.push({
      id: "configure_oauth",
      title: "Enable Supabase OAuth Server",
      status:
        options.verification?.authGateObserved &&
        options.verification.resourceUrlVerified
          ? "complete"
          : "needs_user_action",
      detail:
        "Enable OAuth Server, set the authorization path to your application consent UI, and enable dynamic client registration when your MCP clients require it.",
      url: options.projectRef
        ? `https://supabase.com/dashboard/project/${options.projectRef}/auth/oauth-server`
        : "https://supabase.com/dashboard",
    });
  }

  steps.push({
    id: "verify_remote",
    title: "Verify the deployed MCP endpoint",
    status: endpointVerified
      ? "complete"
      : options.remoteAttempted && !options.remoteReady
        ? "blocked"
        : "ready",
    detail:
      options.verifyDetail ??
      (options.remoteReady && options.remoteAttempted
        ? options.auth === "oauth" && endpointVerified
          ? "OAuth discovery and access protection are ready. Sign in from an MCP client to test authenticated tool access."
          : "The endpoint is responding. Supply a credential to test a complete MCP connection."
        : endpoint
          ? "Probe the deployed endpoint and its authentication contract."
          : "Pass --url or --project-ref so doctor can probe the deployed endpoint."),
    command: endpoint
      ? `npx chumbo doctor --function ${options.functionName} --url ${endpoint}${options.auth === "api-key" ? ` --token <${apiKeyStrategy === "static" ? "MCP_API_KEY" : "APPLICATION_API_KEY"}>` : options.auth === "bearer" ? " --token <USER_JWT>" : ""} --json`
      : `npx chumbo doctor --function ${options.functionName} --url <MCP_URL> --json`,
  });

  if (endpointVerified) {
    steps.push({
      id: "connect_client",
      title: "Connect an MCP client",
      status: "ready",
      detail: "Use the endpoint as the remote MCP server URL.",
      ...(endpoint ? { url: endpoint } : {}),
    });
  }

  const nextActions = steps.filter((step) =>
    ["ready", "needs_user_action", "blocked", "skipped"].includes(step.status),
  );

  return {
    schemaVersion: 1,
    command: options.command,
    status: overallStatus(options, steps),
    projectRoot: options.projectRoot,
    functionName: options.functionName,
    auth: options.auth,
    localEndpoint,
    ...(options.auth === "api-key" ? { authStrategy: apiKeyStrategy } : {}),
    ...(endpoint ? { endpoint } : {}),
    ...(upstreamEndpoint ? { upstreamEndpoint } : {}),
    files: options.files,
    steps,
    nextActions,
    resumeCommand: `npx chumbo setup --resume --function ${options.functionName} --auth ${options.auth} --yes --json`,
    agentHandoff: {
      documentationServerUrl: SUPA_MCP_DOCUMENTATION_SERVER_URL,
      prompt:
        "Inspect this project and implement the authenticated-tools pattern.",
      skillInstallCommand: "npx chumbo skill install --yes --json",
    },
    ...(options.verification ? { verification: options.verification } : {}),
  };
}

function humanCommand(command: string): string {
  return command.replace(" --yes --json", "").replace(" --json", "");
}

export function formatSetupReport(report: SetupReport): string {
  const completed = report.steps.filter((step) => step.status === "complete");
  const lines = [
    "",
    report.status === "complete"
      ? "Your Chumbo is live and verified."
      : report.verification?.runtimeReached
        ? "Your Chumbo is deployed and responding."
        : report.status === "planned" || report.status === "needs_confirmation"
          ? "Setup plan ready."
          : "Your Chumbo scaffold is ready.",
  ];
  if (completed.length > 0) {
    lines.push("", "Done:");
    for (const step of completed) lines.push(`  ✓ ${step.title}`);
  }
  if (report.nextActions.length > 0) {
    lines.push("", "Next:");
    report.nextActions.forEach((step, index) => {
      lines.push(`  ${index + 1}. ${step.title}`);
      lines.push(`     ${step.detail}`);
      if (step.command) lines.push(`     ${humanCommand(step.command)}`);
      if (step.url) lines.push(`     ${step.url}`);
    });
  }
  if (report.endpoint) lines.push("", `MCP URL: ${report.endpoint}`);
  lines.push("", `Resume anytime: ${humanCommand(report.resumeCommand)}`);
  lines.push(
    "Agent mode: add --json for stable machine-readable steps and next actions.",
  );
  lines.push(
    "",
    "Build with an agent:",
    `  MCP docs: ${report.agentHandoff.documentationServerUrl}`,
    `  Agent skill (recommended): ${humanCommand(report.agentHandoff.skillInstallCommand)}`,
    `  Ask: “${report.agentHandoff.prompt}”`,
  );
  return lines.join("\n");
}
